import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "de", label: "Deutsch" },
  { code: "pt", label: "Português" },
  { code: "zh", label: "中文" },
  { code: "ar", label: "العربية" },
  { code: "hi", label: "हिन्दी" },
];

const translations: Record<string, Record<string, string>> = {
  en: {
    "greeting.morning": "Good Morning",
    "greeting.afternoon": "Good Afternoon",
    "greeting.evening": "Good Evening",
    "balance.available": "Available Balance",
    "account.number": "Your Account Number",
    "dashboard.whatToDo": "What would you like to do today?",
    "dashboard.chooseActions": "Choose from our popular actions below",
    "action.accountInfo": "Account Info",
    "action.sendMoney": "Send Money",
    "action.deposit": "Deposit",
    "action.transactionHistory": "Transaction History",
    "stats.title": "Account Statistics",
    "stats.transactionLimit": "Transaction Limit",
    "stats.pendingTransactions": "Pending Transactions",
    "stats.noPending": "No pending transactions",
    "support.title": "Need Help? Contact Support",
    "support.subtitle": "Chat with our support team",
    "footer.copyright": "© 2026 Silicon Valley Bank. All Rights Reserved.",
    "nav.home": "Home",
    "nav.stats": "Stats",
    "nav.cards": "Cards",
    "nav.profile": "Profile",
    "menu.accountOverview": "Account Overview",
    "menu.transactions": "Transactions",
    "menu.transferMoney": "Transfer Money",
    "menu.cards": "Cards",
    "menu.settings": "Settings",
    "menu.contactSupport": "Contact Support",
    "menu.signOut": "Sign Out",
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to your account",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.rememberMe": "Remember Me",
    "login.signIn": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register",
    "login.fillAll": "Please fill in all fields",
    "login.invalid": "Invalid email or password",
    "login.forgotPassword": "Forgot Password?",
    "login.resetPassword": "Reset Password",
    "login.resetDesc": "Enter your email address and we'll send you a reset code.",
    "login.sendCode": "Send Reset Code",
    "login.backToLogin": "Back to Login",
    "login.codeSentTo": "A reset code has been sent to",
    "login.enterCode": "Enter Reset Code",
    "login.verifyCode": "Verify Code",
    "login.invalidCode": "Invalid code. Please try again.",
    "login.emailNotFound": "Email address not found.",
    "login.enterNewPassword": "Enter your new password below.",
    "login.passwordResetSuccess": "Password reset successfully! You can now log in.",
    "page.accountInfo": "Account Information",
    "page.transactions": "Transactions",
    "page.cards": "My Cards",
    "page.settings": "Settings",
    "page.contact": "Contact Support",
    "page.deposit": "Deposit Funds",
    "page.transfer": "Send Money",
    "transfer.recipient": "Recipient Name",
    "transfer.recipientPlaceholder": "Enter recipient's full name",
    "transfer.country": "Select Country",
    "transfer.destCountry": "Destination Country",
    "transfer.amount": "Amount (USD)",
    "transfer.reason": "Reason for Transfer",
    "transfer.reasonPlaceholder": "e.g. Family support, Business payment",
    "transfer.continue": "Continue",
    "transfer.confirm": "Confirm Transfer",
    "transfer.reviewDetails": "Please review the details below before proceeding.",
    "transfer.summary": "Transfer Summary",
    "transfer.fee": "Transfer Fee",
    "transfer.total": "Total Amount",
    "transfer.enterOtp": "Enter Verification Code",
    "transfer.otpSent": "We've sent a 6-digit code to your email",
    "transfer.otpSentTo": "Verification code sent to",
    "transfer.verify": "Verify & Complete",
    "transfer.success": "Transaction Pending Review",
    "transfer.successDesc": "Your transfer of",
    "transfer.to": "to",
    "transfer.pending": "is being processed.",
    "transfer.backHome": "Back to Dashboard",
    "transfer.makeAnother": "Make Another Transfer",
    "transfer.edit": "Edit",
    "transfer.confirmProceed": "Confirm & Proceed",
    "transfer.enterPin": "Enter Transaction PIN",
    "transfer.enterPinDesc": "Enter your 4-digit transaction PIN to continue.",
    "transfer.verifyPin": "Verify PIN",
    "transfer.invalidPin": "Invalid PIN. Please try again.",
    "transfer.setPinFirst": "Please set a transaction PIN in Settings > Security first.",
    "transfer.securityVerification": "Security Verification",
    "transfer.otpDesc": "Enter the OTP code to complete your transaction.",
    "transfer.contactAdmin": "⚠ Please contact the cashier desk via support to receive your OTP code.",
    "transfer.adminOtpNote": "The OTP will be provided by the Admin Manager.",
    "transfer.enterOtpPlaceholder": "Enter 6-digit code",
    "transfer.invalidOtp": "Invalid verification code.",
    "transfer.needHelp": "Need help?",
    "transfer.contactSupport": "Contact Support",
    "transfer.fillFields": "Please fill in all required fields.",
    "transfer.pleaseEnter": "Please enter",
    "transfer.invalidAmount": "Enter a valid amount.",
    "transfer.insufficientBalance": "Insufficient balance.",
    "deposit.cardPayment": "Card Payment",
    "deposit.bankTransfer": "Bank Transfer",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Select Card Type",
    "deposit.cardNumber": "Card Number",
    "deposit.expiry": "Expiry Date",
    "deposit.cvv": "CVV",
    "deposit.amount": "Amount (USD)",
    "deposit.proceed": "Proceed with Deposit",
    "deposit.transferTo": "Make transfer to your account number below",
    "deposit.btcAddress": "Bitcoin Wallet Address",
    "deposit.scanQr": "Scan QR code to deposit",
    "account.fullName": "Full Name",
    "account.email": "Email",
    "account.accountNumber": "Account Number",
    "account.status": "Account Status",
    "account.country": "Country",
    "account.language": "Language",
    "account.balance": "Available Balance",
    "settings.personalInfo": "Personal Information",
    "settings.personalSub": "Name, email, phone",
    "settings.langRegion": "Language & Region",
    "settings.security": "Security",
    "settings.securitySub": "Password, PIN, 2FA",
    "settings.notifications": "Notifications",
    "settings.notificationsSub": "Phone, email alerts",
    "settings.signOut": "Sign Out",
    "settings.firstName": "First Name",
    "settings.lastName": "Last Name",
    "settings.phone": "Phone Number",
    "settings.saveChanges": "Save Changes",
    "settings.saved": "Changes saved successfully!",
    "settings.selectLanguage": "Select your preferred language",
    "settings.langChanged": "Language changed to",
    "settings.changePassword": "Change Password",
    "settings.oldPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmNewPassword": "Confirm New Password",
    "settings.updatePassword": "Update Password",
    "settings.passwordMismatch": "Passwords do not match.",
    "settings.passwordTooShort": "Password must be at least 8 characters.",
    "settings.wrongPassword": "Current password is incorrect.",
    "settings.passwordChanged": "Password updated successfully!",
    "settings.transactionPin": "Transaction PIN",
    "settings.createPin": "Create a 4-digit PIN for transaction security.",
    "settings.pinExists": "Update your 4-digit transaction PIN.",
    "settings.enterPin": "Enter PIN",
    "settings.confirmPin": "Confirm PIN",
    "settings.setPin": "Set PIN",
    "settings.updatePin": "Update PIN",
    "settings.pinLength": "PIN must be 4 digits.",
    "settings.pinMismatch": "PINs do not match.",
    "settings.pinSet": "Transaction PIN set successfully!",
    "settings.contactDetails": "Contact Details",
    "settings.notSet": "Not set",
    "settings.notifDesc": "You will receive notifications via email and phone for login activity, transaction updates, and security alerts.",
    "contact.sendMessage": "Send Message",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.fillAll": "Please fill all fields",
    "contact.sent": "Message sent! We'll get back to you soon.",
    "chat.help": "How may we help you?",
    "notif.title": "Notifications",
  },
  fr: {
    "greeting.morning": "Bonjour",
    "greeting.afternoon": "Bon après-midi",
    "greeting.evening": "Bonsoir",
    "balance.available": "Solde disponible",
    "account.number": "Votre numéro de compte",
    "dashboard.whatToDo": "Que souhaitez-vous faire aujourd'hui ?",
    "dashboard.chooseActions": "Choisissez parmi nos actions populaires",
    "action.accountInfo": "Infos du compte",
    "action.sendMoney": "Envoyer de l'argent",
    "action.deposit": "Dépôt",
    "action.transactionHistory": "Historique des transactions",
    "stats.title": "Statistiques du compte",
    "stats.transactionLimit": "Limite de transaction",
    "stats.pendingTransactions": "Transactions en attente",
    "stats.noPending": "Aucune transaction en attente",
    "support.title": "Besoin d'aide ? Contactez le support",
    "support.subtitle": "Discutez avec notre équipe",
    "footer.copyright": "© 2026 Silicon Valley Bank. Tous droits réservés.",
    "nav.home": "Accueil",
    "nav.stats": "Stats",
    "nav.cards": "Cartes",
    "nav.profile": "Profil",
    "menu.accountOverview": "Aperçu du compte",
    "menu.transactions": "Transactions",
    "menu.transferMoney": "Transférer de l'argent",
    "menu.cards": "Cartes",
    "menu.settings": "Paramètres",
    "menu.contactSupport": "Contacter le support",
    "menu.signOut": "Déconnexion",
    "login.title": "Bon retour",
    "login.subtitle": "Connectez-vous à votre compte",
    "login.email": "Adresse e-mail",
    "login.password": "Mot de passe",
    "login.rememberMe": "Se souvenir de moi",
    "login.signIn": "Se connecter",
    "login.noAccount": "Pas de compte ?",
    "login.register": "S'inscrire",
    "login.fillAll": "Veuillez remplir tous les champs",
    "login.invalid": "E-mail ou mot de passe invalide",
    "login.forgotPassword": "Mot de passe oublié ?",
    "login.resetPassword": "Réinitialiser le mot de passe",
    "login.resetDesc": "Entrez votre adresse e-mail et nous vous enverrons un code.",
    "login.sendCode": "Envoyer le code",
    "login.backToLogin": "Retour à la connexion",
    "login.codeSentTo": "Un code a été envoyé à",
    "login.enterCode": "Entrez le code",
    "login.verifyCode": "Vérifier le code",
    "login.invalidCode": "Code invalide. Réessayez.",
    "login.emailNotFound": "Adresse e-mail introuvable.",
    "login.enterNewPassword": "Entrez votre nouveau mot de passe ci-dessous.",
    "login.passwordResetSuccess": "Mot de passe réinitialisé avec succès !",
    "page.accountInfo": "Informations du compte",
    "page.transactions": "Transactions",
    "page.cards": "Mes cartes",
    "page.settings": "Paramètres",
    "page.contact": "Contacter le support",
    "page.deposit": "Déposer des fonds",
    "page.transfer": "Envoyer de l'argent",
    "transfer.recipient": "Nom du destinataire",
    "transfer.recipientPlaceholder": "Nom complet du destinataire",
    "transfer.country": "Sélectionner le pays",
    "transfer.destCountry": "Pays de destination",
    "transfer.amount": "Montant (USD)",
    "transfer.reason": "Raison du transfert",
    "transfer.reasonPlaceholder": "ex. Aide familiale, Paiement commercial",
    "transfer.continue": "Continuer",
    "transfer.confirm": "Confirmer le transfert",
    "transfer.reviewDetails": "Veuillez vérifier les détails ci-dessous.",
    "transfer.fee": "Frais de transfert",
    "transfer.total": "Montant total",
    "transfer.verify": "Vérifier et terminer",
    "transfer.success": "Transaction en attente d'examen",
    "transfer.successDesc": "Votre transfert de",
    "transfer.to": "à",
    "transfer.pending": "est en cours de traitement.",
    "transfer.backHome": "Retour au tableau de bord",
    "transfer.makeAnother": "Effectuer un autre transfert",
    "transfer.edit": "Modifier",
    "transfer.confirmProceed": "Confirmer et procéder",
    "transfer.enterPin": "Entrez votre PIN",
    "transfer.enterPinDesc": "Entrez votre PIN de transaction à 4 chiffres.",
    "transfer.verifyPin": "Vérifier le PIN",
    "transfer.invalidPin": "PIN invalide. Réessayez.",
    "transfer.setPinFirst": "Veuillez définir un PIN dans Paramètres > Sécurité.",
    "transfer.securityVerification": "Vérification de sécurité",
    "transfer.otpDesc": "Entrez le code OTP pour compléter votre transaction.",
    "transfer.contactAdmin": "⚠ Veuillez contacter le guichet via le support pour recevoir votre code OTP.",
    "transfer.adminOtpNote": "L'OTP sera fourni par l'administrateur.",
    "transfer.enterOtpPlaceholder": "Entrez le code à 6 chiffres",
    "transfer.invalidOtp": "Code de vérification invalide.",
    "transfer.needHelp": "Besoin d'aide ?",
    "transfer.contactSupport": "Contacter le support",
    "transfer.fillFields": "Veuillez remplir tous les champs requis.",
    "transfer.pleaseEnter": "Veuillez entrer",
    "transfer.invalidAmount": "Entrez un montant valide.",
    "transfer.insufficientBalance": "Solde insuffisant.",
    "deposit.cardPayment": "Paiement par carte",
    "deposit.bankTransfer": "Virement bancaire",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Sélectionner le type de carte",
    "deposit.cardNumber": "Numéro de carte",
    "deposit.expiry": "Date d'expiration",
    "deposit.cvv": "CVV",
    "deposit.amount": "Montant (USD)",
    "deposit.proceed": "Procéder au dépôt",
    "deposit.transferTo": "Effectuez un virement vers votre numéro de compte ci-dessous",
    "deposit.btcAddress": "Adresse du portefeuille Bitcoin",
    "deposit.scanQr": "Scannez le code QR pour déposer",
    "account.fullName": "Nom complet",
    "account.email": "E-mail",
    "account.accountNumber": "Numéro de compte",
    "account.status": "Statut du compte",
    "account.country": "Pays",
    "account.language": "Langue",
    "account.balance": "Solde disponible",
    "settings.personalInfo": "Informations personnelles",
    "settings.personalSub": "Nom, e-mail, téléphone",
    "settings.langRegion": "Langue et région",
    "settings.security": "Sécurité",
    "settings.securitySub": "Mot de passe, PIN, 2FA",
    "settings.notifications": "Notifications",
    "settings.notificationsSub": "Téléphone, alertes e-mail",
    "settings.signOut": "Déconnexion",
    "settings.firstName": "Prénom",
    "settings.lastName": "Nom de famille",
    "settings.phone": "Numéro de téléphone",
    "settings.saveChanges": "Enregistrer",
    "settings.saved": "Modifications enregistrées !",
    "settings.selectLanguage": "Sélectionnez votre langue préférée",
    "settings.langChanged": "Langue changée en",
    "settings.changePassword": "Changer le mot de passe",
    "settings.oldPassword": "Mot de passe actuel",
    "settings.newPassword": "Nouveau mot de passe",
    "settings.confirmNewPassword": "Confirmer le nouveau mot de passe",
    "settings.updatePassword": "Mettre à jour",
    "settings.passwordMismatch": "Les mots de passe ne correspondent pas.",
    "settings.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères.",
    "settings.wrongPassword": "Le mot de passe actuel est incorrect.",
    "settings.passwordChanged": "Mot de passe mis à jour !",
    "settings.transactionPin": "PIN de transaction",
    "settings.createPin": "Créez un PIN à 4 chiffres pour la sécurité.",
    "settings.pinExists": "Mettez à jour votre PIN de transaction.",
    "settings.enterPin": "Entrez le PIN",
    "settings.confirmPin": "Confirmez le PIN",
    "settings.setPin": "Définir le PIN",
    "settings.updatePin": "Mettre à jour le PIN",
    "settings.pinLength": "Le PIN doit contenir 4 chiffres.",
    "settings.pinMismatch": "Les PINs ne correspondent pas.",
    "settings.pinSet": "PIN défini avec succès !",
    "settings.contactDetails": "Coordonnées",
    "settings.notSet": "Non défini",
    "settings.notifDesc": "Vous recevrez des notifications par e-mail et téléphone.",
    "contact.sendMessage": "Envoyer un message",
    "contact.name": "Nom",
    "contact.email": "E-mail",
    "contact.message": "Message",
    "contact.fillAll": "Veuillez remplir tous les champs",
    "contact.sent": "Message envoyé ! Nous vous répondrons bientôt.",
    "chat.help": "Comment pouvons-nous vous aider ?",
    "notif.title": "Notifications",
  },
  es: {
    "greeting.morning": "Buenos días",
    "greeting.afternoon": "Buenas tardes",
    "greeting.evening": "Buenas noches",
    "balance.available": "Saldo disponible",
    "account.number": "Su número de cuenta",
    "dashboard.whatToDo": "¿Qué le gustaría hacer hoy?",
    "dashboard.chooseActions": "Elija entre nuestras acciones populares",
    "action.accountInfo": "Info de cuenta",
    "action.sendMoney": "Enviar dinero",
    "action.deposit": "Depósito",
    "action.transactionHistory": "Historial de transacciones",
    "stats.title": "Estadísticas de cuenta",
    "stats.transactionLimit": "Límite de transacción",
    "stats.pendingTransactions": "Transacciones pendientes",
    "stats.noPending": "Sin transacciones pendientes",
    "support.title": "¿Necesita ayuda? Contacte soporte",
    "support.subtitle": "Chatee con nuestro equipo",
    "footer.copyright": "© 2026 Silicon Valley Bank. Todos los derechos reservados.",
    "nav.home": "Inicio",
    "nav.stats": "Estadísticas",
    "nav.cards": "Tarjetas",
    "nav.profile": "Perfil",
    "menu.accountOverview": "Resumen de cuenta",
    "menu.transactions": "Transacciones",
    "menu.transferMoney": "Transferir dinero",
    "menu.cards": "Tarjetas",
    "menu.settings": "Configuración",
    "menu.contactSupport": "Contactar soporte",
    "menu.signOut": "Cerrar sesión",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Inicie sesión en su cuenta",
    "login.email": "Correo electrónico",
    "login.password": "Contraseña",
    "login.rememberMe": "Recordarme",
    "login.signIn": "Iniciar sesión",
    "login.noAccount": "¿No tiene cuenta?",
    "login.register": "Registrarse",
    "login.fillAll": "Por favor complete todos los campos",
    "login.invalid": "Correo o contraseña inválidos",
    "login.forgotPassword": "¿Olvidó su contraseña?",
    "login.resetPassword": "Restablecer contraseña",
    "login.resetDesc": "Ingrese su correo y le enviaremos un código.",
    "login.sendCode": "Enviar código",
    "login.backToLogin": "Volver al inicio de sesión",
    "login.codeSentTo": "Se ha enviado un código a",
    "login.enterCode": "Ingrese el código",
    "login.verifyCode": "Verificar código",
    "login.invalidCode": "Código inválido. Intente de nuevo.",
    "login.emailNotFound": "Correo no encontrado.",
    "login.enterNewPassword": "Ingrese su nueva contraseña.",
    "login.passwordResetSuccess": "¡Contraseña restablecida exitosamente!",
    "page.accountInfo": "Información de cuenta",
    "page.transactions": "Transacciones",
    "page.cards": "Mis tarjetas",
    "page.settings": "Configuración",
    "page.contact": "Contactar soporte",
    "page.deposit": "Depositar fondos",
    "page.transfer": "Enviar dinero",
    "transfer.recipient": "Nombre del destinatario",
    "transfer.recipientPlaceholder": "Nombre completo del destinatario",
    "transfer.country": "Seleccionar país",
    "transfer.destCountry": "País de destino",
    "transfer.amount": "Monto (USD)",
    "transfer.reason": "Motivo de la transferencia",
    "transfer.reasonPlaceholder": "ej. Apoyo familiar, Pago comercial",
    "transfer.continue": "Continuar",
    "transfer.confirm": "Confirmar transferencia",
    "transfer.reviewDetails": "Revise los detalles a continuación.",
    "transfer.fee": "Tarifa de transferencia",
    "transfer.total": "Monto total",
    "transfer.verify": "Verificar y completar",
    "transfer.success": "Transacción pendiente de revisión",
    "transfer.successDesc": "Su transferencia de",
    "transfer.to": "a",
    "transfer.pending": "está siendo procesada.",
    "transfer.backHome": "Volver al panel",
    "transfer.makeAnother": "Hacer otra transferencia",
    "transfer.edit": "Editar",
    "transfer.confirmProceed": "Confirmar y proceder",
    "transfer.enterPin": "Ingrese su PIN",
    "transfer.enterPinDesc": "Ingrese su PIN de transacción de 4 dígitos.",
    "transfer.verifyPin": "Verificar PIN",
    "transfer.invalidPin": "PIN inválido. Intente de nuevo.",
    "transfer.setPinFirst": "Configure un PIN en Configuración > Seguridad.",
    "transfer.securityVerification": "Verificación de seguridad",
    "transfer.otpDesc": "Ingrese el código OTP para completar su transacción.",
    "transfer.contactAdmin": "⚠ Contacte la mesa de caja a través del soporte para recibir su código OTP.",
    "transfer.adminOtpNote": "El OTP será proporcionado por el administrador.",
    "transfer.enterOtpPlaceholder": "Ingrese código de 6 dígitos",
    "transfer.invalidOtp": "Código de verificación inválido.",
    "transfer.needHelp": "¿Necesita ayuda?",
    "transfer.contactSupport": "Contactar soporte",
    "transfer.fillFields": "Complete todos los campos requeridos.",
    "transfer.pleaseEnter": "Por favor ingrese",
    "transfer.invalidAmount": "Ingrese un monto válido.",
    "transfer.insufficientBalance": "Saldo insuficiente.",
    "deposit.cardPayment": "Pago con tarjeta",
    "deposit.bankTransfer": "Transferencia bancaria",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Seleccionar tipo de tarjeta",
    "deposit.cardNumber": "Número de tarjeta",
    "deposit.expiry": "Fecha de vencimiento",
    "deposit.cvv": "CVV",
    "deposit.amount": "Monto (USD)",
    "deposit.proceed": "Proceder con el depósito",
    "deposit.transferTo": "Realice una transferencia a su número de cuenta",
    "deposit.btcAddress": "Dirección de billetera Bitcoin",
    "deposit.scanQr": "Escanee el código QR para depositar",
    "account.fullName": "Nombre completo",
    "account.email": "Correo",
    "account.accountNumber": "Número de cuenta",
    "account.status": "Estado de cuenta",
    "account.country": "País",
    "account.language": "Idioma",
    "account.balance": "Saldo disponible",
    "settings.personalInfo": "Información personal",
    "settings.personalSub": "Nombre, correo, teléfono",
    "settings.langRegion": "Idioma y región",
    "settings.security": "Seguridad",
    "settings.securitySub": "Contraseña, PIN, 2FA",
    "settings.notifications": "Notificaciones",
    "settings.notificationsSub": "Teléfono, alertas de correo",
    "settings.signOut": "Cerrar sesión",
    "settings.firstName": "Nombre",
    "settings.lastName": "Apellido",
    "settings.phone": "Teléfono",
    "settings.saveChanges": "Guardar cambios",
    "settings.saved": "¡Cambios guardados!",
    "settings.selectLanguage": "Seleccione su idioma preferido",
    "settings.langChanged": "Idioma cambiado a",
    "settings.changePassword": "Cambiar contraseña",
    "settings.oldPassword": "Contraseña actual",
    "settings.newPassword": "Nueva contraseña",
    "settings.confirmNewPassword": "Confirmar nueva contraseña",
    "settings.updatePassword": "Actualizar contraseña",
    "settings.passwordMismatch": "Las contraseñas no coinciden.",
    "settings.passwordTooShort": "La contraseña debe tener al menos 8 caracteres.",
    "settings.wrongPassword": "La contraseña actual es incorrecta.",
    "settings.passwordChanged": "¡Contraseña actualizada!",
    "settings.transactionPin": "PIN de transacción",
    "settings.createPin": "Cree un PIN de 4 dígitos para seguridad.",
    "settings.pinExists": "Actualice su PIN de transacción.",
    "settings.enterPin": "Ingrese PIN",
    "settings.confirmPin": "Confirme PIN",
    "settings.setPin": "Establecer PIN",
    "settings.updatePin": "Actualizar PIN",
    "settings.pinLength": "El PIN debe tener 4 dígitos.",
    "settings.pinMismatch": "Los PINs no coinciden.",
    "settings.pinSet": "¡PIN establecido!",
    "settings.contactDetails": "Datos de contacto",
    "settings.notSet": "No establecido",
    "settings.notifDesc": "Recibirá notificaciones por correo y teléfono.",
    "contact.sendMessage": "Enviar mensaje",
    "contact.name": "Nombre",
    "contact.email": "Correo",
    "contact.message": "Mensaje",
    "contact.fillAll": "Por favor complete todos los campos",
    "contact.sent": "¡Mensaje enviado! Le responderemos pronto.",
    "chat.help": "¿Cómo podemos ayudarle?",
    "notif.title": "Notificaciones",
  },
  de: {
    "greeting.morning": "Guten Morgen",
    "greeting.afternoon": "Guten Tag",
    "greeting.evening": "Guten Abend",
    "balance.available": "Verfügbares Guthaben",
    "account.number": "Ihre Kontonummer",
    "dashboard.whatToDo": "Was möchten Sie heute tun?",
    "dashboard.chooseActions": "Wählen Sie aus unseren beliebten Aktionen",
    "action.accountInfo": "Kontoinformationen",
    "action.sendMoney": "Geld senden",
    "action.deposit": "Einzahlung",
    "action.transactionHistory": "Transaktionsverlauf",
    "stats.title": "Kontostatistiken",
    "stats.transactionLimit": "Transaktionslimit",
    "stats.pendingTransactions": "Ausstehende Transaktionen",
    "stats.noPending": "Keine ausstehenden Transaktionen",
    "support.title": "Hilfe benötigt? Support kontaktieren",
    "support.subtitle": "Chatten Sie mit unserem Team",
    "footer.copyright": "© 2026 Silicon Valley Bank. Alle Rechte vorbehalten.",
    "nav.home": "Start",
    "nav.stats": "Statistik",
    "nav.cards": "Karten",
    "nav.profile": "Profil",
    "menu.signOut": "Abmelden",
    "login.title": "Willkommen zurück",
    "login.subtitle": "Melden Sie sich an",
    "login.email": "E-Mail-Adresse",
    "login.password": "Passwort",
    "login.rememberMe": "Angemeldet bleiben",
    "login.signIn": "Anmelden",
    "login.noAccount": "Kein Konto?",
    "login.register": "Registrieren",
    "login.forgotPassword": "Passwort vergessen?",
    "login.resetPassword": "Passwort zurücksetzen",
    "login.resetDesc": "Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Code.",
    "login.sendCode": "Code senden",
    "login.backToLogin": "Zurück zur Anmeldung",
    "login.codeSentTo": "Ein Code wurde gesendet an",
    "login.enterCode": "Code eingeben",
    "login.verifyCode": "Code überprüfen",
    "login.invalidCode": "Ungültiger Code.",
    "login.emailNotFound": "E-Mail nicht gefunden.",
    "login.enterNewPassword": "Geben Sie Ihr neues Passwort ein.",
    "login.passwordResetSuccess": "Passwort erfolgreich zurückgesetzt!",
    "page.accountInfo": "Kontoinformationen",
    "page.transactions": "Transaktionen",
    "page.cards": "Meine Karten",
    "page.settings": "Einstellungen",
    "page.contact": "Support kontaktieren",
    "page.deposit": "Geld einzahlen",
    "page.transfer": "Geld senden",
    "settings.firstName": "Vorname",
    "settings.lastName": "Nachname",
    "settings.phone": "Telefonnummer",
    "settings.saveChanges": "Speichern",
    "settings.changePassword": "Passwort ändern",
    "settings.oldPassword": "Aktuelles Passwort",
    "settings.newPassword": "Neues Passwort",
    "settings.confirmNewPassword": "Neues Passwort bestätigen",
    "settings.updatePassword": "Passwort aktualisieren",
    "settings.transactionPin": "Transaktions-PIN",
    "settings.createPin": "Erstellen Sie eine 4-stellige PIN.",
    "settings.enterPin": "PIN eingeben",
    "settings.confirmPin": "PIN bestätigen",
    "settings.setPin": "PIN festlegen",
    "settings.contactDetails": "Kontaktdaten",
    "settings.notSet": "Nicht festgelegt",
    "chat.help": "Wie können wir Ihnen helfen?",
    "notif.title": "Benachrichtigungen",
    "transfer.enterPin": "Transaktions-PIN eingeben",
    "transfer.enterPinDesc": "Geben Sie Ihre 4-stellige PIN ein.",
    "transfer.verifyPin": "PIN überprüfen",
    "transfer.contactAdmin": "⚠ Kontaktieren Sie den Support für Ihren OTP-Code.",
    "transfer.adminOtpNote": "Der OTP wird vom Administrator bereitgestellt.",
  },
  pt: {
    "greeting.morning": "Bom dia",
    "greeting.afternoon": "Boa tarde",
    "greeting.evening": "Boa noite",
    "balance.available": "Saldo disponível",
    "account.number": "Seu número de conta",
    "dashboard.whatToDo": "O que você gostaria de fazer hoje?",
    "dashboard.chooseActions": "Escolha entre nossas ações populares",
    "action.accountInfo": "Info da conta",
    "action.sendMoney": "Enviar dinheiro",
    "action.deposit": "Depósito",
    "action.transactionHistory": "Histórico de transações",
    "stats.title": "Estatísticas da conta",
    "stats.transactionLimit": "Limite de transação",
    "stats.pendingTransactions": "Transações pendentes",
    "stats.noPending": "Nenhuma transação pendente",
    "support.title": "Precisa de ajuda? Contate o suporte",
    "support.subtitle": "Converse com nossa equipe",
    "footer.copyright": "© 2026 Silicon Valley Bank. Todos os direitos reservados.",
    "nav.home": "Início",
    "nav.stats": "Estatísticas",
    "nav.cards": "Cartões",
    "nav.profile": "Perfil",
    "menu.signOut": "Sair",
    "login.title": "Bem-vindo de volta",
    "login.subtitle": "Entre na sua conta",
    "login.email": "Endereço de e-mail",
    "login.password": "Senha",
    "login.rememberMe": "Lembrar-me",
    "login.signIn": "Entrar",
    "login.forgotPassword": "Esqueceu a senha?",
    "login.resetPassword": "Redefinir senha",
    "login.resetDesc": "Digite seu e-mail e enviaremos um código.",
    "login.sendCode": "Enviar código",
    "login.backToLogin": "Voltar ao login",
    "page.accountInfo": "Informações da conta",
    "page.transactions": "Transações",
    "page.cards": "Meus cartões",
    "page.settings": "Configurações",
    "page.contact": "Contatar suporte",
    "page.deposit": "Depositar fundos",
    "page.transfer": "Enviar dinheiro",
    "settings.firstName": "Nome",
    "settings.lastName": "Sobrenome",
    "settings.phone": "Telefone",
    "settings.saveChanges": "Salvar",
    "settings.changePassword": "Alterar senha",
    "settings.oldPassword": "Senha atual",
    "settings.newPassword": "Nova senha",
    "settings.confirmNewPassword": "Confirmar nova senha",
    "settings.updatePassword": "Atualizar senha",
    "settings.transactionPin": "PIN de transação",
    "settings.createPin": "Crie um PIN de 4 dígitos.",
    "settings.enterPin": "Digite o PIN",
    "settings.confirmPin": "Confirme o PIN",
    "settings.setPin": "Definir PIN",
    "settings.contactDetails": "Detalhes de contato",
    "settings.notSet": "Não definido",
    "chat.help": "Como podemos ajudá-lo?",
    "notif.title": "Notificações",
    "transfer.enterPin": "Digite o PIN de transação",
    "transfer.enterPinDesc": "Digite seu PIN de 4 dígitos.",
    "transfer.verifyPin": "Verificar PIN",
    "transfer.contactAdmin": "⚠ Entre em contato com o suporte para receber seu código OTP.",
    "transfer.adminOtpNote": "O OTP será fornecido pelo administrador.",
  },
  zh: {
    "greeting.morning": "早上好",
    "greeting.afternoon": "下午好",
    "greeting.evening": "晚上好",
    "balance.available": "可用余额",
    "account.number": "您的账户号码",
    "dashboard.whatToDo": "您今天想做什么？",
    "dashboard.chooseActions": "从我们的热门操作中选择",
    "action.accountInfo": "账户信息",
    "action.sendMoney": "转账",
    "action.deposit": "存款",
    "action.transactionHistory": "交易历史",
    "stats.title": "账户统计",
    "stats.transactionLimit": "交易限额",
    "stats.pendingTransactions": "待处理交易",
    "stats.noPending": "没有待处理交易",
    "support.title": "需要帮助？联系客服",
    "support.subtitle": "与我们的团队聊天",
    "footer.copyright": "© 2026 Silicon Valley Bank. 保留所有权利。",
    "nav.home": "首页",
    "nav.stats": "统计",
    "nav.cards": "卡片",
    "nav.profile": "个人",
    "menu.signOut": "退出",
    "login.title": "欢迎回来",
    "login.subtitle": "登录您的账户",
    "login.email": "电子邮件",
    "login.password": "密码",
    "login.rememberMe": "记住我",
    "login.signIn": "登录",
    "login.forgotPassword": "忘记密码？",
    "login.resetPassword": "重置密码",
    "login.sendCode": "发送代码",
    "login.backToLogin": "返回登录",
    "page.accountInfo": "账户信息",
    "page.transactions": "交易记录",
    "page.cards": "我的卡",
    "page.settings": "设置",
    "page.contact": "联系客服",
    "page.deposit": "存入资金",
    "page.transfer": "转账",
    "settings.firstName": "名",
    "settings.lastName": "姓",
    "settings.phone": "电话号码",
    "settings.saveChanges": "保存",
    "settings.changePassword": "更改密码",
    "settings.oldPassword": "当前密码",
    "settings.newPassword": "新密码",
    "settings.confirmNewPassword": "确认新密码",
    "settings.updatePassword": "更新密码",
    "settings.transactionPin": "交易PIN",
    "settings.createPin": "创建4位数PIN。",
    "settings.enterPin": "输入PIN",
    "settings.confirmPin": "确认PIN",
    "settings.setPin": "设置PIN",
    "settings.contactDetails": "联系方式",
    "settings.notSet": "未设置",
    "chat.help": "我们能帮您什么？",
    "notif.title": "通知",
    "transfer.enterPin": "输入交易PIN",
    "transfer.enterPinDesc": "输入您的4位数交易PIN。",
    "transfer.verifyPin": "验证PIN",
    "transfer.contactAdmin": "⚠ 请联系客服获取您的OTP代码。",
    "transfer.adminOtpNote": "OTP将由管理员提供。",
  },
  ar: {
    "greeting.morning": "صباح الخير",
    "greeting.afternoon": "مساء الخير",
    "greeting.evening": "مساء الخير",
    "balance.available": "الرصيد المتاح",
    "account.number": "رقم حسابك",
    "dashboard.whatToDo": "ماذا تريد أن تفعل اليوم؟",
    "dashboard.chooseActions": "اختر من الإجراءات الشائعة",
    "action.accountInfo": "معلومات الحساب",
    "action.sendMoney": "إرسال أموال",
    "action.deposit": "إيداع",
    "action.transactionHistory": "سجل المعاملات",
    "stats.title": "إحصائيات الحساب",
    "stats.transactionLimit": "حد المعاملات",
    "stats.pendingTransactions": "المعاملات المعلقة",
    "stats.noPending": "لا توجد معاملات معلقة",
    "support.title": "تحتاج مساعدة؟ اتصل بالدعم",
    "support.subtitle": "تحدث مع فريقنا",
    "footer.copyright": "© 2026 Silicon Valley Bank. جميع الحقوق محفوظة.",
    "nav.home": "الرئيسية",
    "nav.stats": "إحصائيات",
    "nav.cards": "البطاقات",
    "nav.profile": "الملف",
    "menu.signOut": "تسجيل الخروج",
    "login.title": "مرحباً بعودتك",
    "login.subtitle": "سجّل الدخول إلى حسابك",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.rememberMe": "تذكرني",
    "login.signIn": "تسجيل الدخول",
    "login.forgotPassword": "نسيت كلمة المرور؟",
    "login.resetPassword": "إعادة تعيين كلمة المرور",
    "login.sendCode": "إرسال الرمز",
    "login.backToLogin": "العودة لتسجيل الدخول",
    "page.accountInfo": "معلومات الحساب",
    "page.transactions": "المعاملات",
    "page.cards": "بطاقاتي",
    "page.settings": "الإعدادات",
    "page.contact": "اتصل بالدعم",
    "page.deposit": "إيداع أموال",
    "page.transfer": "إرسال أموال",
    "settings.firstName": "الاسم الأول",
    "settings.lastName": "اسم العائلة",
    "settings.phone": "رقم الهاتف",
    "settings.saveChanges": "حفظ",
    "settings.changePassword": "تغيير كلمة المرور",
    "settings.oldPassword": "كلمة المرور الحالية",
    "settings.newPassword": "كلمة المرور الجديدة",
    "settings.confirmNewPassword": "تأكيد كلمة المرور الجديدة",
    "settings.updatePassword": "تحديث كلمة المرور",
    "settings.transactionPin": "رمز PIN للمعاملات",
    "settings.createPin": "أنشئ رمز PIN من 4 أرقام.",
    "settings.enterPin": "أدخل PIN",
    "settings.confirmPin": "تأكيد PIN",
    "settings.setPin": "تعيين PIN",
    "settings.contactDetails": "تفاصيل الاتصال",
    "settings.notSet": "غير محدد",
    "chat.help": "كيف يمكننا مساعدتك؟",
    "notif.title": "الإشعارات",
    "transfer.enterPin": "أدخل رمز PIN للمعاملة",
    "transfer.enterPinDesc": "أدخل رمز PIN المكون من 4 أرقام.",
    "transfer.verifyPin": "التحقق من PIN",
    "transfer.contactAdmin": "⚠ يرجى الاتصال بالدعم للحصول على رمز OTP.",
    "transfer.adminOtpNote": "سيتم توفير OTP من قبل المدير.",
  },
  hi: {
    "greeting.morning": "सुप्रभात",
    "greeting.afternoon": "नमस्कार",
    "greeting.evening": "शुभ संध्या",
    "balance.available": "उपलब्ध शेष",
    "account.number": "आपका खाता नंबर",
    "dashboard.whatToDo": "आज आप क्या करना चाहेंगे?",
    "dashboard.chooseActions": "हमारी लोकप्रिय कार्रवाइयों में से चुनें",
    "action.accountInfo": "खाता जानकारी",
    "action.sendMoney": "पैसे भेजें",
    "action.deposit": "जमा",
    "action.transactionHistory": "लेनदेन इतिहास",
    "stats.title": "खाता सांख्यिकी",
    "stats.transactionLimit": "लेनदेन सीमा",
    "stats.pendingTransactions": "लंबित लेनदेन",
    "stats.noPending": "कोई लंबित लेनदेन नहीं",
    "support.title": "मदद चाहिए? सहायता से संपर्क करें",
    "support.subtitle": "हमारी टीम से चैट करें",
    "footer.copyright": "© 2026 Silicon Valley Bank. सर्वाधिकार सुरक्षित।",
    "nav.home": "होम",
    "nav.stats": "आँकड़े",
    "nav.cards": "कार्ड",
    "nav.profile": "प्रोफ़ाइल",
    "menu.signOut": "साइन आउट",
    "login.title": "वापसी पर स्वागत है",
    "login.subtitle": "अपने खाते में साइन इन करें",
    "login.email": "ईमेल पता",
    "login.password": "पासवर्ड",
    "login.rememberMe": "मुझे याद रखें",
    "login.signIn": "साइन इन",
    "login.forgotPassword": "पासवर्ड भूल गए?",
    "login.resetPassword": "पासवर्ड रीसेट करें",
    "login.sendCode": "कोड भेजें",
    "login.backToLogin": "लॉगिन पर वापस जाएं",
    "page.accountInfo": "खाता जानकारी",
    "page.transactions": "लेनदेन",
    "page.cards": "मेरे कार्ड",
    "page.settings": "सेटिंग्स",
    "page.contact": "सहायता से संपर्क करें",
    "page.deposit": "राशि जमा करें",
    "page.transfer": "पैसे भेजें",
    "settings.firstName": "पहला नाम",
    "settings.lastName": "उपनाम",
    "settings.phone": "फोन नंबर",
    "settings.saveChanges": "सहेजें",
    "settings.changePassword": "पासवर्ड बदलें",
    "settings.oldPassword": "वर्तमान पासवर्ड",
    "settings.newPassword": "नया पासवर्ड",
    "settings.confirmNewPassword": "नए पासवर्ड की पुष्टि करें",
    "settings.updatePassword": "पासवर्ड अपडेट करें",
    "settings.transactionPin": "लेनदेन PIN",
    "settings.createPin": "4 अंकों का PIN बनाएं।",
    "settings.enterPin": "PIN दर्ज करें",
    "settings.confirmPin": "PIN की पुष्टि करें",
    "settings.setPin": "PIN सेट करें",
    "settings.contactDetails": "संपर्क विवरण",
    "settings.notSet": "सेट नहीं",
    "chat.help": "हम आपकी कैसे मदद कर सकते हैं?",
    "notif.title": "सूचनाएं",
    "transfer.enterPin": "लेनदेन PIN दर्ज करें",
    "transfer.enterPinDesc": "अपना 4 अंकों का PIN दर्ज करें।",
    "transfer.verifyPin": "PIN सत्यापित करें",
    "transfer.contactAdmin": "⚠ अपना OTP कोड प्राप्त करने के लिए सहायता से संपर्क करें।",
    "transfer.adminOtpNote": "OTP व्यवस्थापक द्वारा प्रदान किया जाएगा।",
  },
};

type LanguageContextType = {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem("svb_lang") || "en");

  const setLang = (code: string) => {
    setLangState(code);
    localStorage.setItem("svb_lang", code);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
