import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "de", label: "Deutsch" },
  { code: "pt", label: "Português" },
  { code: "zh", label: "中文" },
  { code: "ar", label: "العربية" },
  { code: "hi", label: "हिन्दी" },
];

const translations: Record<string, Record<string, string>> = {
  en: {
    "greeting.morning": "Good Morning",
    "greeting.afternoon": "Good Afternoon",
    "greeting.evening": "Good Evening",
    "balance.available": "Available Balance",
    "account.number": "Your Account Number",
    "dashboard.whatToDo": "What would you like to do today?",
    "dashboard.chooseActions": "Choose from our popular actions below",
    "action.accountInfo": "Account Info",
    "action.sendMoney": "Send Money",
    "action.deposit": "Deposit",
    "action.transactionHistory": "Transaction History",
    "stats.title": "Account Statistics",
    "stats.transactionLimit": "Transaction Limit",
    "stats.pendingTransactions": "Pending Transactions",
    "stats.noPending": "No pending transactions",
    "support.title": "Need Help? Contact Support",
    "support.subtitle": "Chat with our support team",
    "footer.copyright": "© 2026 Silicon Valley Bank. All Rights Reserved.",
    "nav.home": "Home",
    "nav.stats": "Stats",
    "nav.cards": "Cards",
    "nav.profile": "Profile",
    "menu.accountOverview": "Account Overview",
    "menu.transactions": "Transactions",
    "menu.transferMoney": "Transfer Money",
    "menu.cards": "Cards",
    "menu.settings": "Settings",
    "menu.contactSupport": "Contact Support",
    "menu.signOut": "Sign Out",
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to your account",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.rememberMe": "Remember Me",
    "login.signIn": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register",
    "login.fillAll": "Please fill in all fields",
    "login.invalid": "Invalid email or password",
    "page.accountInfo": "Account Information",
    "page.transactions": "Transactions",
    "page.cards": "My Cards",
    "page.settings": "Settings",
    "page.contact": "Contact Support",
    "page.deposit": "Deposit Funds",
    "page.transfer": "Send Money",
    "transfer.recipient": "Recipient Name",
    "transfer.country": "Select Country",
    "transfer.amount": "Amount (USD)",
    "transfer.reason": "Reason for Transfer",
    "transfer.continue": "Continue",
    "transfer.confirm": "Confirm Transfer",
    "transfer.summary": "Transfer Summary",
    "transfer.fee": "Transfer Fee",
    "transfer.total": "Total Amount",
    "transfer.enterOtp": "Enter Verification Code",
    "transfer.otpSent": "We've sent a 6-digit code to your email",
    "transfer.verify": "Verify & Complete",
    "transfer.success": "Transfer Submitted",
    "transfer.pending": "Your transfer is under review",
    "transfer.backHome": "Back to Dashboard",
    "deposit.cardPayment": "Card Payment",
    "deposit.bankTransfer": "Bank Transfer",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Select Card Type",
    "deposit.cardNumber": "Card Number",
    "deposit.expiry": "Expiry Date",
    "deposit.cvv": "CVV",
    "deposit.amount": "Amount (USD)",
    "deposit.proceed": "Proceed with Deposit",
    "deposit.transferTo": "Make transfer to your account number below",
    "deposit.btcAddress": "Bitcoin Wallet Address",
    "deposit.scanQr": "Scan QR code to deposit",
    "account.fullName": "Full Name",
    "account.email": "Email",
    "account.accountNumber": "Account Number",
    "account.status": "Account Status",
    "account.country": "Country",
    "account.language": "Language",
    "account.balance": "Available Balance",
    "settings.personalInfo": "Personal Information",
    "settings.personalSub": "Name, email, phone",
    "settings.langRegion": "Language & Region",
    "settings.security": "Security",
    "settings.securitySub": "Password, 2FA",
    "settings.notifications": "Notifications",
    "settings.notificationsSub": "Push, email, SMS",
    "settings.signOut": "Sign Out",
    "contact.sendMessage": "Send Message",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.fillAll": "Please fill all fields",
    "contact.sent": "Message sent! We'll get back to you soon.",
    "chat.help": "How may we help you?",
  },
  fr: {
    "greeting.morning": "Bonjour",
    "greeting.afternoon": "Bon après-midi",
    "greeting.evening": "Bonsoir",
    "balance.available": "Solde disponible",
    "account.number": "Votre numéro de compte",
    "dashboard.whatToDo": "Que souhaitez-vous faire aujourd'hui ?",
    "dashboard.chooseActions": "Choisissez parmi nos actions populaires",
    "action.accountInfo": "Infos du compte",
    "action.sendMoney": "Envoyer de l'argent",
    "action.deposit": "Dépôt",
    "action.transactionHistory": "Historique des transactions",
    "stats.title": "Statistiques du compte",
    "stats.transactionLimit": "Limite de transaction",
    "stats.pendingTransactions": "Transactions en attente",
    "stats.noPending": "Aucune transaction en attente",
    "support.title": "Besoin d'aide ? Contactez le support",
    "support.subtitle": "Discutez avec notre équipe",
    "footer.copyright": "© 2026 Silicon Valley Bank. Tous droits réservés.",
    "nav.home": "Accueil",
    "nav.stats": "Stats",
    "nav.cards": "Cartes",
    "nav.profile": "Profil",
    "menu.accountOverview": "Aperçu du compte",
    "menu.transactions": "Transactions",
    "menu.transferMoney": "Transférer de l'argent",
    "menu.cards": "Cartes",
    "menu.settings": "Paramètres",
    "menu.contactSupport": "Contacter le support",
    "menu.signOut": "Déconnexion",
    "login.title": "Bon retour",
    "login.subtitle": "Connectez-vous à votre compte",
    "login.email": "Adresse e-mail",
    "login.password": "Mot de passe",
    "login.rememberMe": "Se souvenir de moi",
    "login.signIn": "Se connecter",
    "login.noAccount": "Pas de compte ?",
    "login.register": "S'inscrire",
    "login.fillAll": "Veuillez remplir tous les champs",
    "login.invalid": "E-mail ou mot de passe invalide",
    "page.accountInfo": "Informations du compte",
    "page.transactions": "Transactions",
    "page.cards": "Mes cartes",
    "page.settings": "Paramètres",
    "page.contact": "Contacter le support",
    "page.deposit": "Déposer des fonds",
    "page.transfer": "Envoyer de l'argent",
    "transfer.recipient": "Nom du destinataire",
    "transfer.country": "Sélectionner le pays",
    "transfer.amount": "Montant (USD)",
    "transfer.reason": "Raison du transfert",
    "transfer.continue": "Continuer",
    "transfer.confirm": "Confirmer le transfert",
    "transfer.summary": "Résumé du transfert",
    "transfer.fee": "Frais de transfert",
    "transfer.total": "Montant total",
    "transfer.enterOtp": "Entrez le code de vérification",
    "transfer.otpSent": "Nous avons envoyé un code à 6 chiffres à votre e-mail",
    "transfer.verify": "Vérifier et terminer",
    "transfer.success": "Transfert soumis",
    "transfer.pending": "Votre transfert est en cours d'examen",
    "transfer.backHome": "Retour au tableau de bord",
    "deposit.cardPayment": "Paiement par carte",
    "deposit.bankTransfer": "Virement bancaire",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Sélectionner le type de carte",
    "deposit.cardNumber": "Numéro de carte",
    "deposit.expiry": "Date d'expiration",
    "deposit.cvv": "CVV",
    "deposit.amount": "Montant (USD)",
    "deposit.proceed": "Procéder au dépôt",
    "deposit.transferTo": "Effectuez un virement vers votre numéro de compte ci-dessous",
    "deposit.btcAddress": "Adresse du portefeuille Bitcoin",
    "deposit.scanQr": "Scannez le code QR pour déposer",
    "account.fullName": "Nom complet",
    "account.email": "E-mail",
    "account.accountNumber": "Numéro de compte",
    "account.status": "Statut du compte",
    "account.country": "Pays",
    "account.language": "Langue",
    "account.balance": "Solde disponible",
    "settings.personalInfo": "Informations personnelles",
    "settings.personalSub": "Nom, e-mail, téléphone",
    "settings.langRegion": "Langue et région",
    "settings.security": "Sécurité",
    "settings.securitySub": "Mot de passe, 2FA",
    "settings.notifications": "Notifications",
    "settings.notificationsSub": "Push, e-mail, SMS",
    "settings.signOut": "Déconnexion",
    "contact.sendMessage": "Envoyer un message",
    "contact.name": "Nom",
    "contact.email": "E-mail",
    "contact.message": "Message",
    "contact.fillAll": "Veuillez remplir tous les champs",
    "contact.sent": "Message envoyé ! Nous vous répondrons bientôt.",
    "chat.help": "Comment pouvons-nous vous aider ?",
  },
  es: {
    "greeting.morning": "Buenos días",
    "greeting.afternoon": "Buenas tardes",
    "greeting.evening": "Buenas noches",
    "balance.available": "Saldo disponible",
    "account.number": "Su número de cuenta",
    "dashboard.whatToDo": "¿Qué le gustaría hacer hoy?",
    "dashboard.chooseActions": "Elija entre nuestras acciones populares",
    "action.accountInfo": "Info de cuenta",
    "action.sendMoney": "Enviar dinero",
    "action.deposit": "Depósito",
    "action.transactionHistory": "Historial de transacciones",
    "stats.title": "Estadísticas de cuenta",
    "stats.transactionLimit": "Límite de transacción",
    "stats.pendingTransactions": "Transacciones pendientes",
    "stats.noPending": "Sin transacciones pendientes",
    "support.title": "¿Necesita ayuda? Contacte soporte",
    "support.subtitle": "Chatee con nuestro equipo",
    "footer.copyright": "© 2026 Silicon Valley Bank. Todos los derechos reservados.",
    "nav.home": "Inicio",
    "nav.stats": "Estadísticas",
    "nav.cards": "Tarjetas",
    "nav.profile": "Perfil",
    "menu.accountOverview": "Resumen de cuenta",
    "menu.transactions": "Transacciones",
    "menu.transferMoney": "Transferir dinero",
    "menu.cards": "Tarjetas",
    "menu.settings": "Configuración",
    "menu.contactSupport": "Contactar soporte",
    "menu.signOut": "Cerrar sesión",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Inicie sesión en su cuenta",
    "login.email": "Correo electrónico",
    "login.password": "Contraseña",
    "login.rememberMe": "Recordarme",
    "login.signIn": "Iniciar sesión",
    "login.noAccount": "¿No tiene cuenta?",
    "login.register": "Registrarse",
    "login.fillAll": "Por favor complete todos los campos",
    "login.invalid": "Correo o contraseña inválidos",
    "page.accountInfo": "Información de cuenta",
    "page.transactions": "Transacciones",
    "page.cards": "Mis tarjetas",
    "page.settings": "Configuración",
    "page.contact": "Contactar soporte",
    "page.deposit": "Depositar fondos",
    "page.transfer": "Enviar dinero",
    "transfer.recipient": "Nombre del destinatario",
    "transfer.country": "Seleccionar país",
    "transfer.amount": "Monto (USD)",
    "transfer.reason": "Motivo de la transferencia",
    "transfer.continue": "Continuar",
    "transfer.confirm": "Confirmar transferencia",
    "transfer.summary": "Resumen de transferencia",
    "transfer.fee": "Tarifa de transferencia",
    "transfer.total": "Monto total",
    "transfer.enterOtp": "Ingrese el código de verificación",
    "transfer.otpSent": "Hemos enviado un código de 6 dígitos a su correo",
    "transfer.verify": "Verificar y completar",
    "transfer.success": "Transferencia enviada",
    "transfer.pending": "Su transferencia está en revisión",
    "transfer.backHome": "Volver al panel",
    "deposit.cardPayment": "Pago con tarjeta",
    "deposit.bankTransfer": "Transferencia bancaria",
    "deposit.bitcoin": "Bitcoin",
    "deposit.selectCard": "Seleccionar tipo de tarjeta",
    "deposit.cardNumber": "Número de tarjeta",
    "deposit.expiry": "Fecha de vencimiento",
    "deposit.cvv": "CVV",
    "deposit.amount": "Monto (USD)",
    "deposit.proceed": "Proceder con el depósito",
    "deposit.transferTo": "Realice una transferencia a su número de cuenta",
    "deposit.btcAddress": "Dirección de billetera Bitcoin",
    "deposit.scanQr": "Escanee el código QR para depositar",
    "account.fullName": "Nombre completo",
    "account.email": "Correo",
    "account.accountNumber": "Número de cuenta",
    "account.status": "Estado de cuenta",
    "account.country": "País",
    "account.language": "Idioma",
    "account.balance": "Saldo disponible",
    "settings.personalInfo": "Información personal",
    "settings.personalSub": "Nombre, correo, teléfono",
    "settings.langRegion": "Idioma y región",
    "settings.security": "Seguridad",
    "settings.securitySub": "Contraseña, 2FA",
    "settings.notifications": "Notificaciones",
    "settings.notificationsSub": "Push, correo, SMS",
    "settings.signOut": "Cerrar sesión",
    "contact.sendMessage": "Enviar mensaje",
    "contact.name": "Nombre",
    "contact.email": "Correo",
    "contact.message": "Mensaje",
    "contact.fillAll": "Por favor complete todos los campos",
    "contact.sent": "¡Mensaje enviado! Le responderemos pronto.",
    "chat.help": "¿Cómo podemos ayudarle?",
  },
  de: {
    "greeting.morning": "Guten Morgen",
    "greeting.afternoon": "Guten Tag",
    "greeting.evening": "Guten Abend",
    "balance.available": "Verfügbares Guthaben",
    "account.number": "Ihre Kontonummer",
    "dashboard.whatToDo": "Was möchten Sie heute tun?",
    "dashboard.chooseActions": "Wählen Sie aus unseren beliebten Aktionen",
    "action.accountInfo": "Kontoinformationen",
    "action.sendMoney": "Geld senden",
    "action.deposit": "Einzahlung",
    "action.transactionHistory": "Transaktionsverlauf",
    "stats.title": "Kontostatistiken",
    "stats.transactionLimit": "Transaktionslimit",
    "stats.pendingTransactions": "Ausstehende Transaktionen",
    "stats.noPending": "Keine ausstehenden Transaktionen",
    "support.title": "Hilfe benötigt? Support kontaktieren",
    "support.subtitle": "Chatten Sie mit unserem Team",
    "footer.copyright": "© 2026 Silicon Valley Bank. Alle Rechte vorbehalten.",
    "nav.home": "Start",
    "nav.stats": "Statistik",
    "nav.cards": "Karten",
    "nav.profile": "Profil",
    "menu.signOut": "Abmelden",
    "login.title": "Willkommen zurück",
    "login.subtitle": "Melden Sie sich an",
    "login.email": "E-Mail-Adresse",
    "login.password": "Passwort",
    "login.rememberMe": "Angemeldet bleiben",
    "login.signIn": "Anmelden",
    "login.noAccount": "Kein Konto?",
    "login.register": "Registrieren",
    "page.accountInfo": "Kontoinformationen",
    "page.transactions": "Transaktionen",
    "page.cards": "Meine Karten",
    "page.settings": "Einstellungen",
    "page.contact": "Support kontaktieren",
    "page.deposit": "Geld einzahlen",
    "page.transfer": "Geld senden",
    "chat.help": "Wie können wir Ihnen helfen?",
  },
  pt: {
    "greeting.morning": "Bom dia",
    "greeting.afternoon": "Boa tarde",
    "greeting.evening": "Boa noite",
    "balance.available": "Saldo disponível",
    "account.number": "Seu número de conta",
    "dashboard.whatToDo": "O que você gostaria de fazer hoje?",
    "dashboard.chooseActions": "Escolha entre nossas ações populares",
    "action.accountInfo": "Info da conta",
    "action.sendMoney": "Enviar dinheiro",
    "action.deposit": "Depósito",
    "action.transactionHistory": "Histórico de transações",
    "stats.title": "Estatísticas da conta",
    "stats.transactionLimit": "Limite de transação",
    "stats.pendingTransactions": "Transações pendentes",
    "stats.noPending": "Nenhuma transação pendente",
    "support.title": "Precisa de ajuda? Contate o suporte",
    "support.subtitle": "Converse com nossa equipe",
    "footer.copyright": "© 2026 Silicon Valley Bank. Todos os direitos reservados.",
    "nav.home": "Início",
    "nav.stats": "Estatísticas",
    "nav.cards": "Cartões",
    "nav.profile": "Perfil",
    "menu.signOut": "Sair",
    "login.title": "Bem-vindo de volta",
    "login.subtitle": "Entre na sua conta",
    "login.email": "Endereço de e-mail",
    "login.password": "Senha",
    "login.rememberMe": "Lembrar-me",
    "login.signIn": "Entrar",
    "page.accountInfo": "Informações da conta",
    "page.transactions": "Transações",
    "page.cards": "Meus cartões",
    "page.settings": "Configurações",
    "page.contact": "Contatar suporte",
    "page.deposit": "Depositar fundos",
    "page.transfer": "Enviar dinheiro",
    "chat.help": "Como podemos ajudá-lo?",
  },
  zh: {
    "greeting.morning": "早上好",
    "greeting.afternoon": "下午好",
    "greeting.evening": "晚上好",
    "balance.available": "可用余额",
    "account.number": "您的账户号码",
    "dashboard.whatToDo": "您今天想做什么？",
    "dashboard.chooseActions": "从我们的热门操作中选择",
    "action.accountInfo": "账户信息",
    "action.sendMoney": "转账",
    "action.deposit": "存款",
    "action.transactionHistory": "交易历史",
    "stats.title": "账户统计",
    "stats.transactionLimit": "交易限额",
    "stats.pendingTransactions": "待处理交易",
    "stats.noPending": "没有待处理交易",
    "support.title": "需要帮助？联系客服",
    "support.subtitle": "与我们的团队聊天",
    "footer.copyright": "© 2026 Silicon Valley Bank. 保留所有权利。",
    "nav.home": "首页",
    "nav.stats": "统计",
    "nav.cards": "卡片",
    "nav.profile": "个人",
    "menu.signOut": "退出",
    "login.title": "欢迎回来",
    "login.subtitle": "登录您的账户",
    "login.email": "电子邮件",
    "login.password": "密码",
    "login.rememberMe": "记住我",
    "login.signIn": "登录",
    "page.accountInfo": "账户信息",
    "page.transactions": "交易记录",
    "page.cards": "我的卡",
    "page.settings": "设置",
    "page.contact": "联系客服",
    "page.deposit": "存入资金",
    "page.transfer": "转账",
    "chat.help": "我们能帮您什么？",
  },
  ar: {
    "greeting.morning": "صباح الخير",
    "greeting.afternoon": "مساء الخير",
    "greeting.evening": "مساء الخير",
    "balance.available": "الرصيد المتاح",
    "account.number": "رقم حسابك",
    "dashboard.whatToDo": "ماذا تريد أن تفعل اليوم؟",
    "dashboard.chooseActions": "اختر من الإجراءات الشائعة",
    "action.accountInfo": "معلومات الحساب",
    "action.sendMoney": "إرسال أموال",
    "action.deposit": "إيداع",
    "action.transactionHistory": "سجل المعاملات",
    "stats.title": "إحصائيات الحساب",
    "stats.transactionLimit": "حد المعاملات",
    "stats.pendingTransactions": "المعاملات المعلقة",
    "stats.noPending": "لا توجد معاملات معلقة",
    "support.title": "تحتاج مساعدة؟ اتصل بالدعم",
    "support.subtitle": "تحدث مع فريقنا",
    "footer.copyright": "© 2026 Silicon Valley Bank. جميع الحقوق محفوظة.",
    "nav.home": "الرئيسية",
    "nav.stats": "إحصائيات",
    "nav.cards": "البطاقات",
    "nav.profile": "الملف",
    "menu.signOut": "تسجيل الخروج",
    "login.title": "مرحباً بعودتك",
    "login.subtitle": "سجّل الدخول إلى حسابك",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.rememberMe": "تذكرني",
    "login.signIn": "تسجيل الدخول",
    "page.accountInfo": "معلومات الحساب",
    "page.transactions": "المعاملات",
    "page.cards": "بطاقاتي",
    "page.settings": "الإعدادات",
    "page.contact": "اتصل بالدعم",
    "page.deposit": "إيداع أموال",
    "page.transfer": "إرسال أموال",
    "chat.help": "كيف يمكننا مساعدتك؟",
  },
  hi: {
    "greeting.morning": "सुप्रभात",
    "greeting.afternoon": "नमस्कार",
    "greeting.evening": "शुभ संध्या",
    "balance.available": "उपलब्ध शेष",
    "account.number": "आपका खाता नंबर",
    "dashboard.whatToDo": "आज आप क्या करना चाहेंगे?",
    "dashboard.chooseActions": "हमारी लोकप्रिय कार्रवाइयों में से चुनें",
    "action.accountInfo": "खाता जानकारी",
    "action.sendMoney": "पैसे भेजें",
    "action.deposit": "जमा",
    "action.transactionHistory": "लेनदेन इतिहास",
    "stats.title": "खाता सांख्यिकी",
    "stats.transactionLimit": "लेनदेन सीमा",
    "stats.pendingTransactions": "लंबित लेनदेन",
    "stats.noPending": "कोई लंबित लेनदेन नहीं",
    "support.title": "मदद चाहिए? सहायता से संपर्क करें",
    "support.subtitle": "हमारी टीम से चैट करें",
    "footer.copyright": "© 2026 Silicon Valley Bank. सर्वाधिकार सुरक्षित।",
    "nav.home": "होम",
    "nav.stats": "आँकड़े",
    "nav.cards": "कार्ड",
    "nav.profile": "प्रोफ़ाइल",
    "menu.signOut": "साइन आउट",
    "login.title": "वापसी पर स्वागत है",
    "login.subtitle": "अपने खाते में साइन इन करें",
    "login.email": "ईमेल पता",
    "login.password": "पासवर्ड",
    "login.rememberMe": "मुझे याद रखें",
    "login.signIn": "साइन इन",
    "page.accountInfo": "खाता जानकारी",
    "page.transactions": "लेनदेन",
    "page.cards": "मेरे कार्ड",
    "page.settings": "सेटिंग्स",
    "page.contact": "सहायता से संपर्क करें",
    "page.deposit": "राशि जमा करें",
    "page.transfer": "पैसे भेजें",
    "chat.help": "हम आपकी कैसे मदद कर सकते हैं?",
  },
};

type LanguageContextType = {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem("svb_lang") || "en");

  const setLang = (code: string) => {
    setLangState(code);
    localStorage.setItem("svb_lang", code);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
